on:
  workflow_call:
    inputs:
      application_environment:
        type: string
        required: false
        default: 'PRODUCTION'

permissions: read-all

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.0.0

      - name: Install Node.js 18 and setup dependency caching
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --prod --ignore-scripts

      - name: Email Workflow URL
        run: node src/index.js --script email-workflow-url --workflow-url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" --email "${{ github.event.client_payload.email }}"
        env:
          NODEMAILER_SERVICE: ${{ secrets.NODEMAILER_SERVICE }}
          NODEMAILER_MAIL_HOST: ${{ secrets.NODEMAILER_MAIL_HOST }}
          NODEMAILER_MAIL_USER: ${{ secrets.NODEMAILER_MAIL_USER }}
          NODEMAILER_MAIL_PASSWORD: ${{ secrets.NODEMAILER_MAIL_PASSWORD }}
          NODEMAILER_MAIL_DISPLAY_USER: ${{ secrets.NODEMAILER_MAIL_DISPLAY_USER }}

      - name: Download and extract submission files
        run: |
          curl -L "${{ github.event.client_payload.submission_url }}?${{ secrets.SUBMISSION_CONTAINER_SAS_TOKEN }}" -o submission.zip
          unzip submission.zip -d submission

      - name: Download and extract question files
        run: |
          curl -L "${{ github.event.client_payload.question_url }}?${{ secrets.QUESTION_CONTAINER_SAS_TOKEN }}" -o question.zip
          unzip question.zip -d question

      - name: Clean unnecessary files
        uses: ./.github/actions/clean

      - name: Restore tests
        uses: ./.github/actions/restore

      - name: Restore inputs
        run: |
          if [ "${{ github.event.client_payload.strict_inputs }}" = "true" ]; then
            rm -rf submission/src
            if [ -d question/src ]; then
              cp -rf question/src ./submission
            fi
          fi

      - name: Install submission dependencies
        run: cd submission && pnpm install --ignore-scripts --fix-lockfile --frozen-lockfile=false

      - name: Install dos2unix
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: dos2unix

      - name: Execute answer script
        run: |
          dos2unix ./submission/execute.sh
          cd submission && bash execute.sh

      - name: Clean unnecessary files
        uses: ./.github/actions/clean
        with:
          preserve_output: true

      - name: Restore tests
        uses: ./.github/actions/restore

      - name: Run tests
        run: cd submission && pnpm dlx jest@29.6.2

      - name: Update score
        run: node src/index.js --script update-score --submission-id "${{ github.event.client_payload.submission_id }}"
        env:
          BASHAWAY_SERVER_URL: ${{ secrets[format('BASHAWAY_{0}_SERVER_URL', inputs.application_environment)] }}
          BASHAWAY_SERVER_API_KEY: ${{ secrets[format('BASHAWAY_{0}_SERVER_API_KEY', inputs.application_environment)] }}
